<!-- minifier: https://www.willpeavy.com/tools/minifier/ -->
<!-- without type="text/css" and type="text/javascript" -->
<!DOCTYPE html>
<html>
	<head>
		<title></title><!-- generated by js -->
		<meta charset="utf-8">
		<?php
			if(file_exists('lib/htmlheaders.min.php')) // local minified
				include('lib/htmlheaders.min.php');
			elseif(file_exists('lib/htmlheaders.php')) // local
				include('lib/htmlheaders.php');
			elseif(file_exists($appImage['address'] . '/lib/htmlheaders.min.php')) // appImage minified
				include($appImage['address'] . '/lib/htmlheaders.min.php');
			else // appImage
				include($appImage['address'] . '/lib/htmlheaders.php');
		?>
	</head>
	<body>
		<div id="nojavascript">
			<h1>Enable javascript to see content</h1>
		</div>
		<div id="header">
			<script type="text/javascript" nonce="9s0c8as0xz">document.getElementById('header').innerHTML=loadingLabel;</script>
		</div>
		<div id="articles"></div>
		<div id="pages"></div>
	</body>
</html>